2024-09-30 15:38:56.224334: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No display found. Using non-interactive Agg backend
Switched to: agg
X_train shape: (13424, 13)
2024-09-30 16:15:46.238819: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No display found. Using non-interactive Agg backend
Switched to: agg
X_train shape: (27224, 13)
2024-09-30 17:27:50.345512: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "cpbandit_m.py", line 511, in <module>
    main()
  File "cpbandit_m.py", line 507, in main
    cpbanit_player._start_game()
  File "cpbandit_m.py", line 380, in _start_game
    self.rewards[k_idx] = observed_utilities
IndexError: list assignment index out of range
No display found. Using non-interactive Agg backend
Switched to: agg
X_train shape: (103235, 13)
2024-10-01 09:16:31.489484: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No display found. Using non-interactive Agg backend
Switched to: agg
Traceback (most recent call last):
  File "cpbandit_m.py", line 65, in <module>
    from get_params import get_params
  File "/usr/scratch1/azhou60/CPBandit_sepsis/get_params.py", line 7, in <module>
    class get_params():
  File "/usr/scratch1/azhou60/CPBandit_sepsis/get_params.py", line 14, in get_params
    max_u_tp=max_u_tp,
NameError: name 'max_u_tp' is not defined
2024-10-01 09:17:29.703115: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No display found. Using non-interactive Agg backend
Switched to: agg
Traceback (most recent call last):
  File "cpbandit_m.py", line 515, in <module>
    main()
  File "cpbandit_m.py", line 509, in main
    ['ridge']]  
TypeError: list indices must be integers or slices, not str
2024-10-01 09:18:02.644441: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "cpbandit_m.py", line 515, in <module>
    main()
  File "cpbandit_m.py", line 513, in main
    cpbanit_player._start_game()
  File "cpbandit_m.py", line 381, in _start_game
    self.rewards[k_idx] = observed_utilities
IndexError: list assignment index out of range
No display found. Using non-interactive Agg backend
Switched to: agg
X_train shape: (27224, 13)
2024-10-01 09:56:11.729920: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2024-10-01 10:01:31.345364: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "cpbandit_m.py", line 515, in <module>
    main()
  File "cpbandit_m.py", line 513, in main
    cpbanit_player._start_game()
  File "cpbandit_m.py", line 381, in _start_game
    self.rewards[k_idx] = observed_utilities
IndexError: list assignment index out of range
No display found. Using non-interactive Agg backend
Switched to: agg
X_train shape: (27224, 13)
